import * as THREE from 'three';
import { VRButton } from 'three/addons/webxr/VRButton.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';
import { CHAPTERS, createArcadeCabinet, createCabinetShard, createEnemyModel, createEnvironment, createPlayerCraft } from './game-content.js';
import './style.css';

const $=(s)=>document.querySelector(s);
const ui={
  title:$('#title-screen'),hud:$('#hud'),pause:$('#pause-screen'),end:$('#end-screen'),transmission:$('#transmission'),transmissionText:$('#transmission-text'),speaker:$('#speaker'),
  health:$('#health-fill'),score:$('#score-value'),phaseLabel:$('#phase-label'),phaseName:$('#phase-name'),objective:$('#objective'),glitchValue:$('#glitch-value'),glitchRing:$('#glitch-ring'),combo:$('#combo'),
  bossHud:$('#boss-hud'),bossFill:$('#boss-fill'),bossName:$('#boss-name'),endTitle:$('#end-title'),endEyebrow:$('#end-eyebrow'),endCopy:$('#end-copy'),finalScore:$('#final-score'),xrNote:$('#xr-note'),
  tutorial:$('#tutorial'),tutorialIndex:$('#tutorial-index'),tutorialKey:$('#tutorial-key'),tutorialTitle:$('#tutorial-title'),tutorialCopy:$('#tutorial-copy'),tutorialProgress:$('#tutorial-progress'),
  manual:$('#control-manual'),controlRibbon:$('#control-ribbon'),worldIntro:$('#world-intro'),worldNumber:$('#world-number'),worldTitle:$('#world-title'),worldRule:$('#world-rule'),worldProgress:$('#world-progress'),levelValue:$('#level-value'),
};

const automatedCapture=navigator.webdriver===true;
const params=new URLSearchParams(location.search);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const scene=new THREE.Scene();scene.background=new THREE.Color(0x02030a);scene.fog=new THREE.FogExp2(0x060814,.018);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.08,120);const desktopCamera={position:new THREE.Vector3(0,8.4,14.2),target:new THREE.Vector3(0,.7,-2.7)};camera.position.copy(desktopCamera.position);camera.lookAt(desktopCamera.target);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(automatedCapture?1:Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.xr.enabled=true;$('#scene').appendChild(renderer.domElement);renderer.domElement.tabIndex=0;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),1.08,.7,.2);composer.addPass(bloom);
const cinema=new ShaderPass({uniforms:{tDiffuse:{value:null},time:{value:0},resolution:{value:new THREE.Vector2(innerWidth,innerHeight)},rupture:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D tDiffuse;uniform float time;uniform vec2 resolution;uniform float rupture;varying vec2 vUv;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec2 p=vUv-.5;float edge=smoothstep(.18,.78,length(p));float tear=sin(vUv.y*72.+time*8.)*rupture*.002;vec2 off=p*(.002+rupture*.01)*edge+vec2(tear,0.);vec3 c=vec3(texture2D(tDiffuse,vUv+off).r,texture2D(tDiffuse,vUv).g,texture2D(tDiffuse,vUv-off).b);c*=.985+.015*sin(vUv.y*resolution.y*1.12);c+=(h(vUv*resolution+time)-.5)*.018;c*=1.-edge*.26;gl_FragColor=vec4(c,1.);}`});composer.addPass(cinema);composer.addPass(new OutputPass());

const worldRoot=new THREE.Group(),arcadeRoot=new THREE.Group(),entityRoot=new THREE.Group(),projectileRoot=new THREE.Group(),effectsRoot=new THREE.Group();scene.add(worldRoot,arcadeRoot,entityRoot,projectileRoot,effectsRoot);
scene.add(new THREE.HemisphereLight(0x496d96,0x09070a,1.15));const sun=new THREE.DirectionalLight(0xd9edff,2.7);sun.position.set(-8,14,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-16;sun.shadow.camera.right=16;sun.shadow.camera.top=16;sun.shadow.camera.bottom=-16;scene.add(sun);const worldLight=new THREE.PointLight(0x61eaff,55,34,2);worldLight.position.set(0,6,-2);scene.add(worldLight);const warmLight=new THREE.PointLight(0xff3b9a,32,25,2);warmLight.position.set(-8,3,3);scene.add(warmLight);

const textureLoader=new THREE.TextureLoader(),textures=new Array(CHAPTERS.length);function worldTexture(index){if(!textures[index])textures[index]=textureLoader.load(CHAPTERS[index].texture,()=>{if(automatedCapture)render();});return textures[index];}
const circuit=textureLoader.load('/assets/corruption-circuit-v1.png',()=>{if(automatedCapture)render();});circuit.colorSpace=THREE.SRGBColorSpace;circuit.wrapS=circuit.wrapT=THREE.RepeatWrapping;circuit.repeat.set(2.4,2.4);
const physical=(color,emissive=0,intensity=0,roughness=.38,metalness=.62)=>new THREE.MeshPhysicalMaterial({color,emissive,emissiveIntensity:intensity,roughness,metalness,clearcoat:.75,clearcoatRoughness:.14});
const glow=(color,intensity=2)=>physical(new THREE.Color(color).multiplyScalar(.22),color,intensity,.15,.55);

let audioCtx;
function startAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();}
function tone(freq,duration=.08,type='square',volume=.025,slide=0){if(!audioCtx)return;const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),audioCtx.currentTime+duration);gain.gain.setValueAtTime(volume,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+duration);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration);}

function mesh(geo,mat,parent,pos=[0,0,0],rot=[0,0,0],scale=[1,1,1]){const m=new THREE.Mesh(geo,mat);m.position.set(...pos);m.rotation.set(...rot);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function buildArcade(){
  const floorMat=new THREE.MeshPhysicalMaterial({map:circuit,emissiveMap:circuit,emissive:0x17185d,emissiveIntensity:.42,color:0x2b3140,metalness:.62,roughness:.3,clearcoat:1,transparent:true,opacity:.78});
  mesh(new THREE.PlaneGeometry(30,34),floorMat,arcadeRoot,[0,-.09,-2],[-Math.PI/2,0,0]);
  const carpetMat=new THREE.MeshStandardMaterial({color:0x090914,roughness:.94});for(const x of [-8.2,8.2])mesh(new THREE.PlaneGeometry(3.8,31),carpetMat,arcadeRoot,[x,-.075,-2],[-Math.PI/2,0,0]);
  for(const side of [-1,1]){const wallMat=new THREE.MeshPhysicalMaterial({map:circuit,emissiveMap:circuit,emissive:side<0?0x471231:0x07334b,emissiveIntensity:.35,metalness:.8,roughness:.28,transparent:true,opacity:.42,side:THREE.DoubleSide});const wall=mesh(new THREE.PlaneGeometry(32,7.5),wallMat,arcadeRoot,[side*13.2,3.7,-2],[0,side<0?Math.PI/2:-Math.PI/2,0]);wall.name='arcade-wall';for(let z=-12;z<=8;z+=4.8){const post=mesh(new RoundedBoxGeometry(.32,6.8,.42,4,.05),physical(0x11151d,0,0,.25,.88),arcadeRoot,[side*12.85,3.25,z]);mesh(new THREE.BoxGeometry(.06,5.6,.48),glow(side<0?0xff3f9d:0x54ecff,1.6),post,[-side*.19,0,0]);}}
  const ceilingMat=physical(0x0a0c12,0,0,.5,.9);for(let z=-12;z<11;z+=3.8){mesh(new THREE.BoxGeometry(27,.16,.22),ceilingMat,arcadeRoot,[0,9.55,z]);for(const x of [-7,0,7])mesh(new THREE.CylinderGeometry(.045,.045,2.7,10),glow(x===0?0xff4baf:0x5cf5ff,1.8),arcadeRoot,[x,9.38,z],[0,0,Math.PI/2]);}
  const sign=mesh(new RoundedBoxGeometry(7.4,1.15,.24,6,.1),physical(0x090a12,0xff3caa,.5,.18,.85),arcadeRoot,[0,5.7,-12.4]);const signCanvas=document.createElement('canvas');signCanvas.width=1024;signCanvas.height=192;const ctx=signCanvas.getContext('2d');ctx.fillStyle='#05060b';ctx.fillRect(0,0,1024,192);ctx.textAlign='center';ctx.font='900 88px Arial Narrow';ctx.fillStyle='#f4fbff';ctx.shadowColor='#ff3caa';ctx.shadowBlur=30;ctx.fillText('GLITCH INVADERS',512,124);const signTex=new THREE.CanvasTexture(signCanvas);signTex.colorSpace=THREE.SRGBColorSpace;mesh(new THREE.PlaneGeometry(6.9,.92),new THREE.MeshBasicMaterial({map:signTex,toneMapped:false}),sign,[0,0,.14]);
}
buildArcade();

const cabinets=[];CHAPTERS.forEach((chapter,i)=>{const left=i%2===0;const slot=Math.floor(i/2);const c=createArcadeCabinet(chapter,i);c.position.set(left?-11.25:11.25,c.userData.baseY,7.2-slot*4.7);c.rotation.y=left?Math.PI/2:-Math.PI/2;arcadeRoot.add(c);cabinets.push(c);});
const playerMesh=createPlayerCraft();playerMesh.position.set(0,.42,6.5);scene.add(playerMesh);

const state={
  mode:'title',time:0,chapter:0,level:1,progress:0,quota:0,score:0,health:100,glitch:0,combo:0,comboTimer:0,spawnTimer:0,shotCooldown:0,dashCooldown:0,invulnerable:0,
  transitionTime:0,pendingChapter:0,transitionBurst:false,environmentInstalled:false,levelTimer:0,messageTimer:0,shake:0,flash:0,bossHp:0,bossMax:0,
  player:{x:0,z:6.5,vx:0,vz:0,bodyYaw:0,turnVelocity:0},keys:{},xrMove:{x:0,z:0},xrTurn:0,xrDashPressed:false,testXRInput:null,
  tutorialActive:false,tutorialStage:0,tutorialDistance:0,sessionSeed:Math.random(),
};
const entities=[],shots=[],enemyShots=[],effects=[],pickups=[];const fastTest=automatedCapture&&params.get('fast')==='1';let currentEnvironment=null,helpReturnMode='playing';
const xrRig=new THREE.Group();scene.add(xrRig);

function clearGroup(group){while(group.children.length)group.remove(group.children[0]);}
function clearDynamic(){entities.length=0;shots.length=0;enemyShots.length=0;effects.length=0;pickups.length=0;clearGroup(entityRoot);clearGroup(projectileRoot);clearGroup(effectsRoot);}
function levelQuota(chapter=state.chapter,level=state.level){const key=CHAPTERS[chapter].key,value={invaders:8+level*3,asteroids:7+level*3,crossing:1+level,centipede:level,tapper:7+level*3,dig:7+level*3,jungle:1+level,brawler:1,cube:7+level*3}[key]||8;return fastTest?Math.min(value,key==='crossing'||key==='jungle'?1:4):value;}
function difficulty(){return 1+state.chapter*.22+(state.level-1)*.28;}
function showMessage(copy,speaker='MARA // NIGHT ATTENDANT',duration=3.5){ui.speaker.textContent=speaker;ui.transmissionText.textContent=copy;ui.transmission.classList.remove('hidden');state.messageTimer=duration;}
function showWorldCard(eyebrow,title,rule){if(!ui.worldIntro)return;ui.worldNumber.textContent=eyebrow;ui.worldTitle.textContent=title;ui.worldRule.textContent=rule;ui.worldIntro.classList.remove('hidden');}
function hideWorldCard(){ui.worldIntro?.classList.add('hidden');}

function resetPlayer(){Object.assign(state.player,{x:0,z:6.5,vx:0,vz:0,bodyYaw:0,turnVelocity:0});playerMesh.position.set(0,.42,6.5);playerMesh.rotation.set(0,0,0);xrRig.position.set(0,0,6.5);xrRig.rotation.y=0;}
function resetGame(){
  const requestedChapter=automatedCapture?clamp(Number(params.get('world'))||0,0,CHAPTERS.length-1):0;const requestedLevel=automatedCapture?clamp(Number(params.get('level'))||1,1,3):1;
  Object.assign(state,{mode:'transition',time:0,chapter:requestedChapter,level:requestedLevel,progress:0,quota:0,score:0,health:100,glitch:automatedCapture?clamp(Number(params.get('glitch'))||0,0,100):0,combo:0,comboTimer:0,spawnTimer:.2,shotCooldown:0,dashCooldown:0,invulnerable:0,transitionTime:0,pendingChapter:requestedChapter,transitionBurst:false,environmentInstalled:false,levelTimer:0,messageTimer:0,shake:0,flash:0,bossHp:0,bossMax:0,tutorialActive:false,tutorialStage:0,tutorialDistance:0});
  clearDynamic();resetPlayer();ui.title.classList.add('hidden');ui.end.classList.add('hidden');ui.pause.classList.add('hidden');ui.manual.classList.add('hidden');ui.hud.classList.remove('hidden');
  cabinets.forEach((c,i)=>{c.visible=!automatedCapture||i===requestedChapter||i===(requestedChapter+1)%CHAPTERS.length||i===(requestedChapter+CHAPTERS.length-1)%CHAPTERS.length;});
  if(automatedCapture&&params.get('skipIntro')==='1'){installWorld(requestedChapter);state.chapter=requestedChapter;state.level=requestedLevel;startLevel();}else beginTakeover(requestedChapter,true);
}

function beginTakeover(chapter,first=false){
  clearDynamic();state.mode='transition';state.pendingChapter=chapter;state.transitionTime=0;state.transitionBurst=false;state.environmentInstalled=false;state.progress=0;state.level=first?state.level:1;state.shake=.18;
  cabinets.forEach((c,i)=>c.userData.active=i===chapter);const ch=CHAPTERS[chapter];showWorldCard(`CABINET ${String(chapter+1).padStart(2,'0')} // REALITY TAKEOVER`,ch.name,ch.rule);ui.transmission.classList.add('hidden');state.messageTimer=0;
  tone(72,.8,'sawtooth',.045,420);
}
function cabinetExplosion(){
  const c=cabinets[state.pendingChapter],origin=new THREE.Vector3();c.userData.screen.getWorldPosition(origin);
  for(let i=0;i<72;i++){const shard=createCabinetShard(CHAPTERS[state.pendingChapter].color,origin);effectsRoot.add(shard);const toCenter=new THREE.Vector3(-origin.x*.35,(Math.random()-.2)*4,-origin.z*.18-2).normalize();effects.push({mesh:shard,life:1.6+Math.random()*1.5,vx:toCenter.x*(5+Math.random()*9)+(Math.random()-.5)*4,vy:1+Math.random()*6,vz:toCenter.z*(5+Math.random()*9)+(Math.random()-.5)*4,spin:new THREE.Vector3(Math.random()*5,Math.random()*5,Math.random()*5)});}
  for(let i=0;i<5;i++){const ring=mesh(new THREE.TorusGeometry(.7+i*.22,.035,10,64),new THREE.MeshBasicMaterial({color:i%2?CHAPTERS[state.pendingChapter].accent:CHAPTERS[state.pendingChapter].color,transparent:true,opacity:.8,blending:THREE.AdditiveBlending}),effectsRoot,origin.toArray());ring.lookAt(camera.position);effects.push({mesh:ring,life:1.35+i*.12,vx:0,vy:0,vz:0,ring:true,scaleSpeed:5+i});}
  tone(95,.65,'sawtooth',.06,580);state.flash=.85;state.shake=.65;
}
function installWorld(index){
  clearGroup(worldRoot);const ch=CHAPTERS[index];currentEnvironment=createEnvironment(ch,worldTexture(index),renderer);worldRoot.add(currentEnvironment);currentEnvironment.userData.skyMat.opacity=automatedCapture?1:0;state.environmentInstalled=true;
  worldLight.color.set(ch.color);warmLight.color.set(ch.accent);scene.fog.color.set(new THREE.Color(ch.color).multiplyScalar(.055));
  arcadeRoot.traverse((o)=>{if(o.isMesh&&o.name==='arcade-wall'&&o.material)o.material.opacity=.18;});
}
function updateTransition(dt){
  state.transitionTime+=dt*(fastTest?8:1);const t=state.transitionTime,c=cabinets[state.pendingChapter];c.userData.portal.material.opacity=Math.min(.92,t*.75);c.userData.portal.scale.setScalar(1+Math.sin(t*8)*.08+t*.08);c.userData.light.intensity=18+Math.sin(t*12)*9;
  if(t>.55&&!state.transitionBurst){state.transitionBurst=true;cabinetExplosion();}
  if(t>1.05&&!state.environmentInstalled)installWorld(state.pendingChapter);
  if(currentEnvironment){currentEnvironment.userData.skyMat.opacity=clamp((t-1.05)/1.55,0,1);currentEnvironment.scale.setScalar(.82+clamp((t-1.05)/1.8,0,1)*.18);}
  cinema.uniforms.rupture.value=Math.sin(clamp((t-.3)/2.8,0,1)*Math.PI)*.9;
  if(t>3.55){state.chapter=state.pendingChapter;state.level=1;hideWorldCard();startLevel();c.userData.portal.material.opacity=.22;c.userData.light.intensity=4;cinema.uniforms.rupture.value=0;}
}

function startLevel(){
  clearDynamic();state.mode='playing';state.progress=0;state.quota=levelQuota();state.spawnTimer=.08;state.levelTimer=0;state.combo=0;state.bossHp=0;state.bossMax=0;resetPlayer();hideWorldCard();const ch=CHAPTERS[state.chapter];
  state.tutorialActive=state.chapter===0&&state.level===1&&params.get('skipTutorial')!=='1';state.tutorialStage=0;state.tutorialDistance=0;ui.tutorial.classList.toggle('hidden',!state.tutorialActive);ui.tutorial.classList.remove('confirmed');
  if(state.tutorialActive)updateTutorial();else seedLevel();showMessage(`LEVEL ${state.level} // ${ch.rule}`,'CABINET RULESET',3.8);updateUI();
}
function seedLevel(){
  const key=CHAPTERS[state.chapter].key;if(key==='invaders'){const cols=fastTest?2:4+state.level,rows=2;for(let row=0;row<rows;row++)for(let col=0;col<cols;col++)spawnEntity('invader',(col-(cols-1)/2)*2.8,-5.8+row*2.05,{hp:1+Math.floor(state.level/3),vx:1.25*difficulty(),scale:1.35});}
  if(key==='centipede'){for(let i=0;i<state.level;i++)spawnEntity('centipede',(i-(state.level-1)/2)*4,-8+i,{hp:8+state.level*3,boss:true});}
  if(key==='brawler')spawnEntity('fighter',0,-5.4,{hp:14+state.level*8,boss:true,scale:1.7});
  if(key==='cube')createCubePickups();
}
function createCubePickups(){for(let i=0;i<state.quota;i++){const row=Math.floor(i/5),x=(i%5-2)*2,z=-7+row*2.2;const pad=mesh(new RoundedBoxGeometry(1.45,.18,1.45,4,.05),glow(CHAPTERS[state.chapter].color,.65),entityRoot,[x,.08,z]);pickups.push({mesh:pad,x,z,claimed:false});}}

function spawnEntity(type,x,z,options={}){
  const ch=CHAPTERS[state.chapter],model=createEnemyModel(type,options.color||ch.accent,options.size||1);model.position.set(x,options.y??(type==='fighter'?0:type==='car'?.02:.48),z);model.scale.setScalar(options.scale||1);entityRoot.add(model);
  const radii={invader:.75,asteroid:.68,car:1.1,centipede:1.1,patron:.62,burrower:.68,beast:.78,fighter:.8,hopper:.65};const hp=options.hp??({invader:1,asteroid:2,car:3,centipede:12,patron:2,burrower:2,beast:3,fighter:20,hopper:2}[type]||1);
  const e={type,mesh:model,x,z,y:model.position.y,vx:options.vx||0,vz:options.vz||0,hp,maxHp:hp,radius:(radii[type]||.7)*(options.scale||1),age:0,phase:Math.random()*6.28,boss:options.boss||false,size:options.size||1,lane:options.lane||0,minor:options.minor||false};entities.push(e);if(e.boss){state.bossHp=hp;state.bossMax=hp;}return e;
}
function spawnLoop(){
  const key=CHAPTERS[state.chapter].key,d=difficulty();if(key==='asteroids')spawnEntity('asteroid',(Math.random()-.5)*16,-10,{size:.7+Math.random()*.8,hp:2+Math.floor(state.level/2),vx:(Math.random()-.5)*3*d,vz:1.2+Math.random()*1.6*d});
  if(key==='crossing'){const lane=Math.floor(Math.random()*5),z=5-lane*2.7,left=Math.random()>.5;spawnEntity('car',left?-11:11,z,{color:left?0xe74338:0x1e92b6,vx:(left?1:-1)*(4.5+lane*.7)*d,lane,minor:true});}
  if(key==='tapper'){const lanes=[-7,-2.3,2.3,7],x=lanes[Math.floor(Math.random()*lanes.length)];spawnEntity('patron',x,-9,{color:Math.random()>.5?0x314d72:0x65305d,vz:1.5*d,hp:1+Math.floor(state.level/2)});}
  if(key==='dig')spawnEntity('burrower',(Math.random()-.5)*16,-9,{color:Math.random()>.5?0x84542d:0x396d68,vz:1.1*d,hp:1+state.level});
  if(key==='jungle'){const left=Math.random()>.5;spawnEntity('beast',left?-10:10,-7+Math.random()*12,{color:Math.random()>.5?0x7a9b2e:0x945f31,vx:(left?1:-1)*3.2*d,hp:2+state.level,minor:true});}
  if(key==='cube')spawnEntity('hopper',(Math.random()-.5)*12,-8,{color:Math.random()>.5?0x9a55d2:0x4ec9bb,vz:1.6*d,hp:1+state.level,minor:true});
  state.spawnTimer=Math.max(.38,1.25/d)+Math.random()*.55;
}

function burst(x,y,z,color,count=16,speed=4){for(let i=0;i<count;i++){const m=mesh(new THREE.TetrahedronGeometry(.045+Math.random()*.11),new THREE.MeshBasicMaterial({color,transparent:true,opacity:1,blending:THREE.AdditiveBlending}),effectsRoot,[x,y,z]);effects.push({mesh:m,life:.45+Math.random()*.6,vx:(Math.random()-.5)*speed,vy:Math.random()*speed,vz:(Math.random()-.5)*speed,spin:new THREE.Vector3(Math.random()*5,Math.random()*5,Math.random()*5)});}}
function shoot(origin=null,direction=null){if(state.mode!=='playing'||state.shotCooldown>0)return;state.shotCooldown=.13;const dir=direction?direction.clone().normalize():new THREE.Vector3(-Math.sin(state.player.bodyYaw),0,-Math.cos(state.player.bodyYaw));if(Math.abs(dir.y)>.65)dir.y=0;dir.normalize();const start=origin?origin.clone():new THREE.Vector3(state.player.x,.58,state.player.z).addScaledVector(dir,.78),shotSpeed=fastTest?72:19;const m=mesh(new THREE.CapsuleGeometry(.065,.54,5,10),new THREE.MeshBasicMaterial({color:CHAPTERS[state.chapter].color,blending:THREE.AdditiveBlending}),projectileRoot,start.toArray());m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);shots.push({mesh:m,x:start.x,y:start.y,z:start.z,vx:dir.x*shotSpeed,vy:dir.y*shotSpeed,vz:dir.z*shotSpeed,life:1.65,radius:.17});tone(620,.045,'square',.018,260);if(state.tutorialActive&&state.tutorialStage===1){state.tutorialStage=2;completeTutorial();}}
function enemyFire(e){const start=new THREE.Vector3(e.x,e.y+.15,e.z),target=new THREE.Vector3(state.player.x,.5,state.player.z),dir=target.sub(start).normalize();const m=mesh(new THREE.SphereGeometry(.11,12,8),new THREE.MeshBasicMaterial({color:CHAPTERS[state.chapter].accent,blending:THREE.AdditiveBlending}),projectileRoot,start.toArray());enemyShots.push({mesh:m,x:start.x,z:start.z,vx:dir.x*(5+difficulty()),vz:dir.z*(5+difficulty()),life:3,radius:.17});}
function destroyEntity(e,counts=true){const i=entities.indexOf(e);if(i<0)return;entities.splice(i,1);entityRoot.remove(e.mesh);burst(e.x,e.y+.3,e.z,CHAPTERS[state.chapter].color,e.boss?46:18,e.boss?8:5);if(counts&&!e.minor){state.progress++;state.score+=Math.round((e.boss?1600:180)*difficulty());state.glitch=clamp(state.glitch+(e.boss?28:9),0,100);state.combo++;state.comboTimer=2.6;}tone(e.boss?70:150,e.boss?.6:.12,'sawtooth',e.boss?.055:.025,e.boss?500:180);
  if(e.type==='asteroid'&&e.size>1&&counts){for(let n=0;n<2;n++)spawnEntity('asteroid',e.x+(n?-.35:.35),e.z,{size:e.size*.48,hp:1,vx:(n?1:-1)*(3+Math.random()*2),vz:(Math.random()-.5)*5,minor:true});}
}
function damagePlayer(amount,source){if(state.invulnerable>0||state.mode!=='playing')return;state.health=clamp(state.health-amount,0,100);state.invulnerable=.72;state.shake=.42;state.combo=0;burst(state.player.x,.55,state.player.z,0xff345c,24,6);tone(95,.25,'sawtooth',.05,-45);if(state.health<=0)finish(false,source);}
function triggerDash(){if(state.mode==='playing'&&state.dashCooldown<=0){state.dashCooldown=1.1;state.invulnerable=.3;state.shake=.12;tone(155,.12,'sawtooth',.02,340);}}
function glitchPulse(){if(state.mode!=='playing'||state.glitch<100)return;state.glitch=0;state.flash=.8;state.shake=.5;const victims=[...entities];victims.forEach((e)=>{const dist=Math.hypot(e.x-state.player.x,e.z-state.player.z);if(dist<11){e.hp-=e.boss?8:99;if(e.hp<=0)destroyEntity(e);}});burst(state.player.x,.7,state.player.z,0xcaff5c,100,11);tone(58,.8,'sawtooth',.065,760);}

function pollXRInput(){state.xrMove.x=0;state.xrMove.z=0;state.xrTurn=0;if(automatedCapture&&state.testXRInput){state.xrMove.x=state.testXRInput.moveX||0;state.xrMove.z=state.testXRInput.moveZ||0;state.xrTurn=state.testXRInput.turn||0;if(state.testXRInput.dash&&!state.xrDashPressed)triggerDash();state.xrDashPressed=Boolean(state.testXRInput.dash);return;}if(!renderer.xr.isPresenting)return;const sources=[...(renderer.xr.getSession()?.inputSources||[])];let dash=false;sources.forEach((source,i)=>{if(!source.gamepad)return;const a=source.gamepad.axes,ax=a.length>=4?a[2]:(a[0]||0),az=a.length>=4?a[3]:(a[1]||0),hand=source.handedness||(!i?'left':'right');if(hand==='right')state.xrTurn=Math.abs(ax)>.16?ax:0;else{state.xrMove.x=Math.abs(ax)>.14?ax:0;state.xrMove.z=Math.abs(az)>.14?az:0;}dash ||= Boolean(source.gamepad.buttons[3]?.pressed||source.gamepad.buttons[4]?.pressed);});if(dash&&!state.xrDashPressed)triggerDash();state.xrDashPressed=dash;}
function updatePlayer(dt){
  pollXRInput();const px=state.player.x,pz=state.player.z,turn=(state.keys.KeyE?1:0)-(state.keys.KeyQ?1:0)+state.xrTurn;state.player.turnVelocity=THREE.MathUtils.damp(state.player.turnVelocity,turn*2.3,12,dt);state.player.bodyYaw=THREE.MathUtils.euclideanModulo(state.player.bodyYaw-state.player.turnVelocity*dt+Math.PI,Math.PI*2)-Math.PI;
  let lx=(state.keys.KeyD||state.keys.ArrowRight?1:0)-(state.keys.KeyA||state.keys.ArrowLeft?1:0)+state.xrMove.x,lz=(state.keys.KeyS||state.keys.ArrowDown?1:0)-(state.keys.KeyW||state.keys.ArrowUp?1:0)+state.xrMove.z;if(lx||lz){const l=Math.hypot(lx,lz);lx/=l;lz/=l;}const sy=Math.sin(state.player.bodyYaw),cy=Math.cos(state.player.bodyYaw),dx=lx*cy+lz*sy,dz=-lx*sy+lz*cy,speed=fastTest?35:(state.dashCooldown>.72?12:6.3);
  state.player.vx=THREE.MathUtils.damp(state.player.vx,dx*speed,10,dt);state.player.vz=THREE.MathUtils.damp(state.player.vz,dz*speed,10,dt);state.player.x=clamp(state.player.x+state.player.vx*dt,-9.1,9.1);state.player.z=clamp(state.player.z+state.player.vz*dt,-10,8.2);
  playerMesh.position.set(state.player.x,.42,state.player.z);playerMesh.rotation.y=state.player.bodyYaw;playerMesh.rotation.z=-state.player.vx*.04;playerMesh.rotation.x=-state.player.vz*.025;const thrust=.65+Math.min(1.4,Math.hypot(state.player.vx,state.player.vz)/5);playerMesh.userData.flames.forEach((f,i)=>{f.scale.y=thrust*(1+Math.sin(state.time*28+i)*.12);});playerMesh.userData.shield.material.opacity=state.invulnerable>0?.72:.08;playerMesh.userData.shield.rotation.y+=dt*.7;
  if(renderer.xr.isPresenting){xrRig.position.set(state.player.x,0,state.player.z);xrRig.rotation.y=state.player.bodyYaw;}if(state.keys.Space)shoot();
  if(state.tutorialActive&&state.tutorialStage===0){state.tutorialDistance+=Math.hypot(state.player.x-px,state.player.z-pz);ui.tutorialProgress.style.width=`${clamp(state.tutorialDistance/1.5*100,0,100)}%`;if(state.tutorialDistance>=1.5){state.tutorialStage=1;updateTutorial();}}
}

function updateEntities(dt){
  const key=CHAPTERS[state.chapter].key,d=difficulty();state.spawnTimer-=dt;if(state.spawnTimer<=0&&!['invaders','centipede','brawler'].includes(key)&&state.progress<state.quota)spawnLoop();
  let formationBounce=false;for(const e of [...entities]){e.age+=dt;
    if(e.type==='invader'){e.x+=e.vx*dt;e.mesh.position.x=e.x;e.mesh.position.y=.7+Math.sin(e.age*3+e.phase)*.14;e.mesh.rotation.y=Math.sin(e.age*1.8+e.phase)*.25;if(Math.abs(e.x)>8.5)formationBounce=true;if(Math.random()<dt*.055*d)enemyFire(e);if(e.z>6.7)damagePlayer(22,'The alien formation reached the cabinet line.');}
    if(e.type==='asteroid'){e.x+=e.vx*dt;e.z+=e.vz*dt;e.mesh.rotation.x+=dt*.35;e.mesh.rotation.y+=dt*.52;if(e.x>10)e.x=-10;if(e.x<-10)e.x=10;if(e.z>9){e.z=-10;e.x=(Math.random()-.5)*18;}e.mesh.position.set(e.x,e.y+Math.sin(e.age+e.phase)*.35,e.z);}
    if(e.type==='car'||e.type==='beast'){e.x+=e.vx*dt;if(Math.abs(e.x)>12){destroyEntity(e,false);continue;}e.mesh.position.x=e.x;e.mesh.rotation.y=e.vx>0?-Math.PI/2:Math.PI/2;}
    if(e.type==='centipede'){e.z+=dt*(1.25+.22*state.level);e.x=Math.sin(e.age*1.8+e.phase)*7;e.mesh.position.set(e.x,.55+Math.sin(e.age*3)*.12,e.z);e.mesh.rotation.y=Math.cos(e.age*1.8+e.phase)*.65;if(e.z>7){e.z=-9;damagePlayer(18,'The brood breached the fungal line.');}}
    if(e.type==='patron'){e.z+=e.vz*dt;e.mesh.position.z=e.z;e.mesh.rotation.y=Math.sin(e.age*3)*.08;if(e.z>7.7){destroyEntity(e,false);damagePlayer(16,'An unserved patron reached the bar.');}}
    if(e.type==='burrower'){const targetX=state.player.x-e.x;e.vx=THREE.MathUtils.damp(e.vx,Math.sign(targetX)*1.5*d,2,dt);e.x+=e.vx*dt;e.z+=e.vz*dt;e.mesh.position.set(e.x,.35+Math.abs(Math.sin(e.age*4))*.32,e.z);e.mesh.rotation.y=Math.atan2(-e.vx,-e.vz);if(e.z>8){e.z=-9;damagePlayer(15,'A tunnel predator surfaced beneath you.');}}
    if(e.type==='fighter'){const dx=state.player.x-e.x,dz=state.player.z-e.z,dist=Math.hypot(dx,dz);if(dist>2.4){e.x+=dx/dist*1.55*d*dt;e.z+=dz/dist*1.55*d*dt;}e.mesh.position.set(e.x,0,e.z);e.mesh.rotation.y=Math.atan2(dx,dz)+Math.PI;if(Math.random()<dt*.42*d)enemyFire(e);}
    if(e.type==='hopper'){e.x+=Math.sin(e.age*3+e.phase)*dt*2;e.z+=e.vz*dt;e.mesh.position.set(e.x,.35+Math.abs(Math.sin(e.age*4))*1.2,e.z);if(e.z>8){e.z=-9;damagePlayer(12,'A void hopper corrupted your tile.');}}
    if(e.boss){state.bossHp=e.hp;state.bossMax=e.maxHp;}
    if(Math.hypot(e.x-state.player.x,e.z-state.player.z)<e.radius+.55)damagePlayer(e.boss?22:12,`Collision with ${e.type}.`);
  }
  if(formationBounce){entities.filter(e=>e.type==='invader').forEach((e)=>{e.vx*=-1;e.z+=.55;e.mesh.position.z=e.z;});}
  for(const shot of [...shots]){shot.life-=dt;shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;shot.z+=shot.vz*dt;shot.mesh.position.set(shot.x,shot.y,shot.z);const hit=entities.find((e)=>Math.hypot(e.x-shot.x,e.z-shot.z)<e.radius+shot.radius);if(hit){hit.hp--;if(hit.boss)state.bossHp=hit.hp;burst(shot.x,shot.y,shot.z,CHAPTERS[state.chapter].color,6,2);shot.life=0;if(hit.hp<=0)destroyEntity(hit);}if(shot.life<=0||Math.abs(shot.x)>13||Math.abs(shot.z)>14){projectileRoot.remove(shot.mesh);shots.splice(shots.indexOf(shot),1);}}
  for(const shot of [...enemyShots]){shot.life-=dt;shot.x+=shot.vx*dt;shot.z+=shot.vz*dt;shot.mesh.position.set(shot.x,.55,shot.z);if(Math.hypot(shot.x-state.player.x,shot.z-state.player.z)<.65){damagePlayer(9,'Hostile cabinet fire.');shot.life=0;}if(shot.life<=0){projectileRoot.remove(shot.mesh);enemyShots.splice(enemyShots.indexOf(shot),1);}}
  if(key==='crossing'&&state.player.z<-8.6){state.progress++;state.score+=900*state.level;state.player.z=7.6;state.invulnerable=1.1;state.flash=.55;showMessage(`BANK ${state.progress}/${state.quota} REACHED. Traffic pattern accelerated.`,'CROSSING CONTROL',2.2);tone(420,.3,'square',.04,420);}
  if(key==='jungle'&&state.player.z<-8.8){state.progress++;state.score+=1100*state.level;state.player.z=7.6;state.invulnerable=1.1;state.flash=.55;showMessage(`TEMPLE GATE ${state.progress}/${state.quota} BREACHED.`,'EXPEDITION SIGNAL',2.2);}
  if(key==='cube')for(const p of pickups){if(!p.claimed&&Math.hypot(p.x-state.player.x,p.z-state.player.z)<.85){p.claimed=true;p.mesh.material=glow(0xffd85c,2.4);p.mesh.position.y=.2;state.progress++;state.score+=500;state.glitch=clamp(state.glitch+8,0,100);tone(480,.08,'sine',.03,260);}}
}

function checkLevelComplete(){if(state.mode!=='playing'||state.tutorialActive||state.progress<state.quota)return;clearDynamic();state.mode='levelclear';state.levelTimer=0;state.flash=.9;ui.transmission.classList.add('hidden');state.messageTimer=0;tone(220,.6,'square',.05,660);showWorldCard(`WORLD ${state.chapter+1} // LEVEL ${state.level} CLEARED`,'RULESET MASTERED',state.level<3?'The cabinet is increasing speed, armor, and attack density.':'The next cabinet is rupturing. A new genre is escaping.');}
function updateLevelClear(dt){state.levelTimer+=dt*(fastTest?12:1);if(state.levelTimer<2.6)return;if(state.level<3){state.level++;hideWorldCard();startLevel();}else if(state.chapter<CHAPTERS.length-1){beginTakeover(state.chapter+1);}else finish(true);}
function finish(won,reason=''){state.mode=won?'won':'gameover';clearDynamic();hideWorldCard();ui.hud.classList.add('hidden');ui.tutorial.classList.add('hidden');ui.transmission.classList.add('hidden');ui.end.classList.remove('hidden');ui.endEyebrow.textContent=won?'ALL CABINETS LIBERATED':'REALITY COLLAPSED';ui.endTitle.textContent=won?'ARCADE ASCENDANT':'GAME OVER';ui.endCopy.textContent=won?'Nine worlds, twenty-seven escalating levels, one impossible night. The cabinets remember your name.':`${reason} The breach can still be challenged.`;ui.finalScore.textContent=String(Math.floor(state.score)).padStart(6,'0');}

function updateEffects(dt){for(const e of [...effects]){e.life-=dt;if(e.ring){e.mesh.scale.addScalar(dt*e.scaleSpeed);e.mesh.material.opacity=clamp(e.life,0,1);}else{e.mesh.position.x+=e.vx*dt;e.mesh.position.y+=e.vy*dt;e.mesh.position.z+=e.vz*dt;e.vy-=3.5*dt;e.mesh.rotation.x+=e.spin.x*dt;e.mesh.rotation.y+=e.spin.y*dt;e.mesh.rotation.z+=e.spin.z*dt;if(e.mesh.material)e.mesh.material.opacity=clamp(e.life,0,1);}if(e.life<=0){effectsRoot.remove(e.mesh);effects.splice(effects.indexOf(e),1);}}
}
function updateEnvironment(dt){if(!currentEnvironment)return;for(const a of currentEnvironment.userData.animated){if(a.type==='spin')a.mesh.rotation.y+=dt*a.speed;if(a.type==='tumble'){a.mesh.rotation.x+=dt*a.speed;a.mesh.rotation.y+=dt*a.speed*.7;}if(a.type==='float')a.mesh.position.y=a.base+Math.sin(state.time*a.speed+a.phase)*.18;if(a.type==='lane'){a.mesh.position.x+=dt*a.speed;if(Math.abs(a.mesh.position.x)>a.limit)a.mesh.position.x=-Math.sign(a.mesh.position.x)*a.limit;}}}
function updateCabinets(dt){cabinets.forEach((c,i)=>{const active=i===state.chapter||i===state.pendingChapter;c.userData.screenMat.emissiveIntensity=THREE.MathUtils.damp(c.userData.screenMat.emissiveIntensity,active?1.35:.55,4,dt);c.userData.light.intensity=THREE.MathUtils.damp(c.userData.light.intensity,active?5:1.25,4,dt);c.position.y=c.userData.baseY+(active?Math.sin(state.time*2.4+i)*.025:0);c.rotation.z=active?Math.sin(state.time*3+i)*.003:0;});}
function updateTutorial(){if(!state.tutorialActive)return;if(state.tutorialStage===0){ui.tutorialIndex.textContent='SYSTEM CALIBRATION 01 / 02';ui.tutorialKey.textContent='WASD';ui.tutorialTitle.textContent='WALK INSIDE THE CABINET WORLD';ui.tutorialCopy.textContent='Move physically, use WASD, or use the left XR stick. Right stick rotates your body.';ui.tutorialProgress.style.width='0%';}else{ui.tutorialIndex.textContent='SYSTEM CALIBRATION 02 / 02';ui.tutorialKey.textContent='FIRE';ui.tutorialTitle.textContent='BREAK THE FIRST ALIEN';ui.tutorialCopy.textContent='Aim and squeeze either trigger, click, or press Space.';ui.tutorialProgress.style.width='100%';}}
function completeTutorial(){state.tutorialActive=false;ui.tutorial.classList.add('confirmed');ui.tutorialTitle.textContent='CABINET LINK STABLE';ui.tutorialCopy.textContent='Formation assault beginning. Survive all three levels.';setTimeout(()=>ui.tutorial.classList.add('hidden'),700);seedLevel();}

function updateUI(){const ch=CHAPTERS[state.chapter];ui.health.style.width=`${state.health}%`;ui.score.textContent=String(Math.floor(state.score)).padStart(6,'0');ui.phaseLabel.textContent=`WORLD ${String(state.chapter+1).padStart(2,'0')} // LEVEL ${state.level}`;ui.phaseName.textContent=ch.name;ui.objective.textContent=state.mode==='transition'?'CABINET REALITY TRANSFER IN PROGRESS':`${ch.objective} // ${state.progress}/${state.quota}`;ui.glitchValue.textContent=Math.floor(state.glitch);ui.glitchRing.classList.toggle('ready',state.glitch>=100);ui.combo.textContent=`CHAIN x${state.combo}`;ui.combo.classList.toggle('hidden',state.combo<2);ui.controlRibbon.classList.toggle('hidden',state.combo>=2);ui.bossHud.classList.toggle('hidden',state.bossMax<=0);ui.bossFill.style.width=`${state.bossMax?clamp(state.bossHp/state.bossMax*100,0,100):0}%`;if(ui.bossName)ui.bossName.textContent=ch.key==='centipede'?'BROOD CORE':ch.key==='brawler'?'STREET CHAMPION':'CABINET BOSS';if(ui.levelValue)ui.levelValue.textContent=`${state.level}/3`;if(ui.worldProgress)ui.worldProgress.innerHTML=CHAPTERS.map((c,i)=>`<i class="${i<state.chapter?'done':i===state.chapter?'active':''}" style="--world-color:#${new THREE.Color(c.color).getHexString()}" title="${c.name}"></i>`).join('');}

function update(dt){state.time+=dt;state.flash=Math.max(0,state.flash-dt*1.8);state.shake=Math.max(0,state.shake-dt*2.4);state.shotCooldown=Math.max(0,state.shotCooldown-dt);state.dashCooldown=Math.max(0,state.dashCooldown-dt);state.invulnerable=Math.max(0,state.invulnerable-dt);state.comboTimer-=dt;if(state.comboTimer<=0)state.combo=0;if(state.messageTimer>0){state.messageTimer-=dt;if(state.messageTimer<=0)ui.transmission.classList.add('hidden');}
  updateCabinets(dt);updateEnvironment(dt);updateEffects(dt);if(state.mode==='transition')updateTransition(dt);if(state.mode==='playing'){state.levelTimer+=dt;updatePlayer(dt);if(!state.tutorialActive)updateEntities(dt);checkLevelComplete();}if(state.mode==='levelclear')updateLevelClear(dt);
  cinema.uniforms.time.value=state.time;worldLight.intensity=42+Math.sin(state.time*1.7)*7;warmLight.intensity=28+Math.sin(state.time*2.1)*5;if(state.flash>0)renderer.toneMappingExposure=1.18+state.flash*.55;else renderer.toneMappingExposure=THREE.MathUtils.damp(renderer.toneMappingExposure,1.18,5,dt);updateUI();}
function render(){if(!renderer.xr.isPresenting){const shake=state.shake*.12;if(state.mode==='title'){camera.position.set(2.8+Math.sin(state.time*.18)*.35,3.35,11.4);camera.lookAt(9.3,1.9,4.4);worldLight.position.set(8,4,4);worldLight.intensity=48;}else if(state.mode==='transition'){const c=cabinets[state.pendingChapter],side=Math.sign(c.position.x)||1;camera.position.set(-side*2.4+(Math.random()-.5)*shake,4.1+(Math.random()-.5)*shake,11.8);camera.lookAt(c.position.x*.83,1.9,c.position.z-.7);worldLight.position.set(c.position.x*.7,4,c.position.z);worldLight.intensity=62;}else{const close=CHAPTERS[state.chapter].key==='brawler',base=close?new THREE.Vector3(0,4.8,12.2):desktopCamera.position,target=close?new THREE.Vector3(0,1.05,-2.5):desktopCamera.target;camera.position.set(base.x+(Math.random()-.5)*shake,base.y+(Math.random()-.5)*shake,base.z+(Math.random()-.5)*shake);camera.lookAt(target);worldLight.position.set(0,6,-2);}if(automatedCapture)renderer.render(scene,camera);else composer.render();}else renderer.render(scene,camera);}

window.advanceTime=(ms)=>{const steps=Math.max(1,Math.round(ms/(1000/60)));for(let i=0;i<steps;i++)update(1/60);render();};
window.render_game_to_text=()=>JSON.stringify({coordinateSystem:'arena x left(-)/right(+), z cabinet breach(-)/player bank(+), y up',mode:state.mode,world:{index:state.chapter+1,key:CHAPTERS[state.chapter].key,name:CHAPTERS[state.chapter].name,level:state.level,levelsPerWorld:3,progress:state.progress,quota:state.quota,rule:CHAPTERS[state.chapter].rule,transition:+state.transitionTime.toFixed(2)},player:{x:+state.player.x.toFixed(2),z:+state.player.z.toFixed(2),bodyYawDegrees:+THREE.MathUtils.radToDeg(state.player.bodyYaw).toFixed(1),health:state.health,invulnerable:+state.invulnerable.toFixed(2)},resources:{score:state.score,glitch:Math.floor(state.glitch),combo:state.combo},enemies:entities.slice(0,18).map((e)=>({type:e.type,x:+e.x.toFixed(2),z:+e.z.toFixed(2),hp:e.hp,boss:e.boss||undefined})),shots:shots.slice(0,10).map((s)=>({x:+s.x.toFixed(2),z:+s.z.toFixed(2),vx:+s.vx.toFixed(1),vz:+s.vz.toFixed(1)})),tutorial:{active:state.tutorialActive,stage:state.tutorialStage,distance:+state.tutorialDistance.toFixed(2)},paused:state.mode==='paused'});
if(automatedCapture)window.__set_glitch_xr_input=(input)=>{state.testXRInput=input;};

function togglePause(force=false){if(state.mode==='playing'&&!force){state.mode='paused';ui.pause.classList.remove('hidden');ui.hud.classList.add('hidden');ui.tutorial.classList.add('hidden');}else if(state.mode==='paused'){state.mode='playing';ui.pause.classList.add('hidden');ui.hud.classList.remove('hidden');if(state.tutorialActive)ui.tutorial.classList.remove('hidden');renderer.domElement.focus({preventScroll:true});previous=performance.now();}}
function toggleHelp(forceClose=false){const open=!ui.manual.classList.contains('hidden');if(open||forceClose){ui.manual.classList.add('hidden');state.mode=helpReturnMode;if(state.mode==='playing')ui.hud.classList.remove('hidden');return;}if(!['playing','paused'].includes(state.mode))return;helpReturnMode=state.mode;state.mode='help';ui.manual.classList.remove('hidden');ui.pause.classList.add('hidden');ui.hud.classList.add('hidden');}
function toggleFullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.();}
const preventKeys=new Set(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space']);
function keyDown(e){const code=e.code||e.key;state.keys[code]=true;if(preventKeys.has(code))e.preventDefault();if(code==='KeyH'&&!e.repeat){toggleHelp();return;}if(state.mode==='help'){if(code==='Escape')toggleHelp(true);return;}if(code==='Enter'&&!e.repeat){if(state.mode==='title'){startAudio();resetGame();return;}if(state.mode==='playing'||state.mode==='paused'){togglePause();return;}if(state.mode==='gameover'||state.mode==='won'){resetGame();return;}}if(code==='Space')shoot();if(code==='KeyG'&&!e.repeat)glitchPulse();if((code==='ShiftLeft'||code==='ShiftRight')&&!e.repeat)triggerDash();if(code==='KeyP'&&!e.repeat)togglePause();if(code==='KeyF'&&!e.repeat)toggleFullscreen();if(code==='KeyR'&&!e.repeat&&['gameover','won'].includes(state.mode))resetGame();}
document.addEventListener('keydown',keyDown,{capture:true});document.addEventListener('keyup',(e)=>{state.keys[e.code||e.key]=false;},{capture:true});window.addEventListener('blur',()=>{state.keys={};});renderer.domElement.addEventListener('pointerdown',()=>{renderer.domElement.focus({preventScroll:true});startAudio();shoot();});
$('#start-btn').addEventListener('pointerdown',(e)=>{e.preventDefault();startAudio();resetGame();});$('#restart-btn').addEventListener('click',()=>{startAudio();resetGame();});$('#resume-btn').addEventListener('click',()=>togglePause(true));$('#restart-pause-btn').addEventListener('click',resetGame);$('#help-chip').addEventListener('click',()=>toggleHelp());$('#close-help').addEventListener('click',()=>toggleHelp(true));
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);cinema.uniforms.resolution.value.set(innerWidth,innerHeight);});

for(let i=0;i<2;i++){const controller=renderer.xr.getController(i);controller.addEventListener('selectstart',()=>{startAudio();const origin=new THREE.Vector3(),direction=new THREE.Vector3(0,0,-1),rotation=new THREE.Quaternion();controller.getWorldPosition(origin);controller.getWorldQuaternion(rotation);direction.applyQuaternion(rotation);shoot(origin,direction);});const ray=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-1)]),new THREE.LineBasicMaterial({color:i?0xff4aa8:0x5cf5ff,transparent:true,opacity:.75}));ray.scale.z=3;controller.add(ray);xrRig.add(controller);}
renderer.xr.addEventListener('sessionstart',()=>{xrRig.add(camera);camera.position.set(0,1.62,0);camera.rotation.set(0,0,0);if(state.mode==='title')resetGame();playerMesh.visible=false;ui.title.classList.add('hidden');ui.hud.classList.remove('hidden');});
renderer.xr.addEventListener('sessionend',()=>{scene.add(camera);camera.position.copy(desktopCamera.position);camera.lookAt(desktopCamera.target);playerMesh.visible=true;});
if(navigator.xr)navigator.xr.isSessionSupported('immersive-vr').then((ok)=>{ui.xrNote.textContent=ok?'WebXR headset detected. Enter VR to rupture the first cabinet.':'Desktop simulation ready. Connect a WebXR headset for room-scale play.';if(ok){const button=VRButton.createButton(renderer);button.id='vr-entry';document.body.appendChild(button);}});

let previous=performance.now();if(!automatedCapture)renderer.setAnimationLoop((now)=>{const dt=Math.min((now-previous)/1000,.05);previous=now;update(dt);render();});updateUI();render();
